# Generated by Django 3.0.2 on 2020-03-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200120_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fathers_name', models.CharField(max_length=50)),
                ('phone_number_1', models.CharField(max_length=50)),
                ('phone_number_2', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('source', models.CharField(choices=[('1', 'Facebook'), ('2', 'Instagram'), ('3', 'Google'), ('4', 'Tanış məsləhəti')], default='4', max_length=2)),
                ('status', models.CharField(choices=[('5', 'Növbəti'), ('6', 'İmtina et'), ('7', 'Təxirə sal')], default='5', max_length=2)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Note')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RelatedPerson')),
            ],
        ),
    ]
