# Generated by Django 3.0.2 on 2020-01-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('catname', models.CharField(max_length=30)),
                ('catid', models.IntegerField()),
            ],
        ),
    ]
