# Generated by Django 3.0.2 on 2020-01-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200124_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pic',
        ),
        migrations.AddField(
            model_name='news',
            name='picname',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='picurl',
            field=models.CharField(default='-', max_length=130),
        ),
    ]
