# Generated by Django 3.0.2 on 2020-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200129_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='scatid',
            field=models.IntegerField(default=0),
        ),
    ]
