# Generated by Django 3.0.2 on 2020-01-29 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_scatid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='scatid',
            new_name='ocatid',
        ),
    ]
